// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: api_keys.sql

package queries

import (
	"context"
	"time"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAPIKey = `-- name: CreateAPIKey :one

INSERT INTO api_keys (
    tenant_id, name, key_hash, key_prefix, scopes, expires_at
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, tenant_id, name, key_hash, key_prefix, scopes, expires_at, last_used_at, created_at
`

type CreateAPIKeyParams struct {
	TenantID  uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	Name      string             `db:"name" json:"name"`
	KeyHash   string             `db:"key_hash" json:"key_hash"`
	KeyPrefix string             `db:"key_prefix" json:"key_prefix"`
	Scopes    []string           `db:"scopes" json:"scopes"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

// sql/queries/api_keys.sql
func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error) {
	row := q.db.QueryRow(ctx, createAPIKey,
		arg.TenantID,
		arg.Name,
		arg.KeyHash,
		arg.KeyPrefix,
		arg.Scopes,
		arg.ExpiresAt,
	)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Scopes,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys 
WHERE id = $1 AND tenant_id = $2
`

type DeleteAPIKeyParams struct {
	ID       uuid.UUID `db:"id" json:"id"`
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
}

func (q *Queries) DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, arg.ID, arg.TenantID)
	return err
}

const getAPIKeyByHash = `-- name: GetAPIKeyByHash :one
SELECT ak.id, ak.tenant_id, ak.name, ak.key_hash, ak.key_prefix, ak.scopes, ak.expires_at, ak.last_used_at, ak.created_at, t.slug as tenant_slug 
FROM api_keys ak
JOIN tenants t ON ak.tenant_id = t.id
WHERE ak.key_hash = $1 AND (ak.expires_at IS NULL OR ak.expires_at > NOW())
LIMIT 1
`

type GetAPIKeyByHashRow struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	TenantID   uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	Name       string             `db:"name" json:"name"`
	KeyHash    string             `db:"key_hash" json:"key_hash"`
	KeyPrefix  string             `db:"key_prefix" json:"key_prefix"`
	Scopes     []string           `db:"scopes" json:"scopes"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	CreatedAt  time.Time          `db:"created_at" json:"created_at"`
	TenantSlug string             `db:"tenant_slug" json:"tenant_slug"`
}

func (q *Queries) GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error) {
	row := q.db.QueryRow(ctx, getAPIKeyByHash, keyHash)
	var i GetAPIKeyByHashRow
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.Name,
		&i.KeyHash,
		&i.KeyPrefix,
		&i.Scopes,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.TenantSlug,
	)
	return i, err
}

const listTenantAPIKeys = `-- name: ListTenantAPIKeys :many
SELECT id, tenant_id, name, key_prefix, scopes, expires_at, last_used_at, created_at
FROM api_keys 
WHERE tenant_id = $1
ORDER BY created_at DESC
`

type ListTenantAPIKeysRow struct {
	ID         uuid.UUID          `db:"id" json:"id"`
	TenantID   uuid.UUID          `db:"tenant_id" json:"tenant_id"`
	Name       string             `db:"name" json:"name"`
	KeyPrefix  string             `db:"key_prefix" json:"key_prefix"`
	Scopes     []string           `db:"scopes" json:"scopes"`
	ExpiresAt  pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `db:"last_used_at" json:"last_used_at"`
	CreatedAt  time.Time          `db:"created_at" json:"created_at"`
}

func (q *Queries) ListTenantAPIKeys(ctx context.Context, tenantID uuid.UUID) ([]ListTenantAPIKeysRow, error) {
	rows, err := q.db.Query(ctx, listTenantAPIKeys, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantAPIKeysRow{}
	for rows.Next() {
		var i ListTenantAPIKeysRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.Name,
			&i.KeyPrefix,
			&i.Scopes,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys 
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsed, id)
	return err
}
