// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package queries

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	// sql/queries/tenant_users.sql
	AddUserToTenant(ctx context.Context, arg AddUserToTenantParams) (TenantUser, error)
	// sql/queries/api_keys.sql
	CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) (ApiKey, error)
	// sql/queries/events.sql
	CreateEvent(ctx context.Context, arg CreateEventParams) (Event, error)
	// sql/queries/tenants.sql
	CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error)
	// sql/queries/users.sql
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	// sql/queries/webhooks.sql
	CreateWebhookDelivery(ctx context.Context, arg CreateWebhookDeliveryParams) (WebhookDelivery, error)
	DeleteAPIKey(ctx context.Context, arg DeleteAPIKeyParams) error
	GetAPIKeyByHash(ctx context.Context, keyHash string) (GetAPIKeyByHashRow, error)
	GetEventsAfterSequence(ctx context.Context, arg GetEventsAfterSequenceParams) ([]Event, error)
	GetEventsByAggregate(ctx context.Context, arg GetEventsByAggregateParams) ([]Event, error)
	GetEventsByType(ctx context.Context, arg GetEventsByTypeParams) ([]Event, error)
	GetPendingWebhookDeliveries(ctx context.Context, limit int32) ([]WebhookDelivery, error)
	GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error)
	GetTenantBySlug(ctx context.Context, slug string) (Tenant, error)
	GetTenantUser(ctx context.Context, arg GetTenantUserParams) (TenantUser, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (User, error)
	IncrementFailedLoginAttempts(ctx context.Context, id uuid.UUID) error
	ListTenantAPIKeys(ctx context.Context, tenantID uuid.UUID) ([]ListTenantAPIKeysRow, error)
	ListTenantUsers(ctx context.Context, tenantID uuid.UUID) ([]ListTenantUsersRow, error)
	ListTenantsByUser(ctx context.Context, userID uuid.UUID) ([]Tenant, error)
	RemoveUserFromTenant(ctx context.Context, arg RemoveUserFromTenantParams) error
	UpdateAPIKeyLastUsed(ctx context.Context, id uuid.UUID) error
	UpdateTenantUserRole(ctx context.Context, arg UpdateTenantUserRoleParams) error
	UpdateUserLastLogin(ctx context.Context, id uuid.UUID) error
	UpdateWebhookDeliveryFailure(ctx context.Context, arg UpdateWebhookDeliveryFailureParams) error
	UpdateWebhookDeliverySuccess(ctx context.Context, arg UpdateWebhookDeliverySuccessParams) error
	VerifyUserEmail(ctx context.Context, id uuid.UUID) error
}

var _ Querier = (*Queries)(nil)
