// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenant_users.sql

package queries

import (
	"context"
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

const addUserToTenant = `-- name: AddUserToTenant :one

INSERT INTO tenant_users (
    tenant_id, user_id, role, permissions
) VALUES (
    $1, $2, $3, $4
) RETURNING id, tenant_id, user_id, role, permissions, created_at
`

type AddUserToTenantParams struct {
	TenantID    uuid.UUID       `db:"tenant_id" json:"tenant_id"`
	UserID      uuid.UUID       `db:"user_id" json:"user_id"`
	Role        UserRoleEnum    `db:"role" json:"role"`
	Permissions json.RawMessage `db:"permissions" json:"permissions"`
}

// sql/queries/tenant_users.sql
func (q *Queries) AddUserToTenant(ctx context.Context, arg AddUserToTenantParams) (TenantUser, error) {
	row := q.db.QueryRow(ctx, addUserToTenant,
		arg.TenantID,
		arg.UserID,
		arg.Role,
		arg.Permissions,
	)
	var i TenantUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.Permissions,
		&i.CreatedAt,
	)
	return i, err
}

const getTenantUser = `-- name: GetTenantUser :one
SELECT id, tenant_id, user_id, role, permissions, created_at FROM tenant_users
WHERE tenant_id = $1 AND user_id = $2 LIMIT 1
`

type GetTenantUserParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) GetTenantUser(ctx context.Context, arg GetTenantUserParams) (TenantUser, error) {
	row := q.db.QueryRow(ctx, getTenantUser, arg.TenantID, arg.UserID)
	var i TenantUser
	err := row.Scan(
		&i.ID,
		&i.TenantID,
		&i.UserID,
		&i.Role,
		&i.Permissions,
		&i.CreatedAt,
	)
	return i, err
}

const listTenantUsers = `-- name: ListTenantUsers :many
SELECT tu.id, tu.tenant_id, tu.user_id, tu.role, tu.permissions, tu.created_at, u.email, u.first_name, u.last_name
FROM tenant_users tu
JOIN users u ON tu.user_id = u.id
WHERE tu.tenant_id = $1
ORDER BY tu.created_at DESC
`

type ListTenantUsersRow struct {
	ID          uuid.UUID       `db:"id" json:"id"`
	TenantID    uuid.UUID       `db:"tenant_id" json:"tenant_id"`
	UserID      uuid.UUID       `db:"user_id" json:"user_id"`
	Role        UserRoleEnum    `db:"role" json:"role"`
	Permissions json.RawMessage `db:"permissions" json:"permissions"`
	CreatedAt   time.Time       `db:"created_at" json:"created_at"`
	Email       string          `db:"email" json:"email"`
	FirstName   string          `db:"first_name" json:"first_name"`
	LastName    string          `db:"last_name" json:"last_name"`
}

func (q *Queries) ListTenantUsers(ctx context.Context, tenantID uuid.UUID) ([]ListTenantUsersRow, error) {
	rows, err := q.db.Query(ctx, listTenantUsers, tenantID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListTenantUsersRow{}
	for rows.Next() {
		var i ListTenantUsersRow
		if err := rows.Scan(
			&i.ID,
			&i.TenantID,
			&i.UserID,
			&i.Role,
			&i.Permissions,
			&i.CreatedAt,
			&i.Email,
			&i.FirstName,
			&i.LastName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeUserFromTenant = `-- name: RemoveUserFromTenant :exec
DELETE FROM tenant_users 
WHERE tenant_id = $1 AND user_id = $2
`

type RemoveUserFromTenantParams struct {
	TenantID uuid.UUID `db:"tenant_id" json:"tenant_id"`
	UserID   uuid.UUID `db:"user_id" json:"user_id"`
}

func (q *Queries) RemoveUserFromTenant(ctx context.Context, arg RemoveUserFromTenantParams) error {
	_, err := q.db.Exec(ctx, removeUserFromTenant, arg.TenantID, arg.UserID)
	return err
}

const updateTenantUserRole = `-- name: UpdateTenantUserRole :exec
UPDATE tenant_users 
SET role = $3, permissions = $4
WHERE tenant_id = $1 AND user_id = $2
`

type UpdateTenantUserRoleParams struct {
	TenantID    uuid.UUID       `db:"tenant_id" json:"tenant_id"`
	UserID      uuid.UUID       `db:"user_id" json:"user_id"`
	Role        UserRoleEnum    `db:"role" json:"role"`
	Permissions json.RawMessage `db:"permissions" json:"permissions"`
}

func (q *Queries) UpdateTenantUserRole(ctx context.Context, arg UpdateTenantUserRoleParams) error {
	_, err := q.db.Exec(ctx, updateTenantUserRole,
		arg.TenantID,
		arg.UserID,
		arg.Role,
		arg.Permissions,
	)
	return err
}
