// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tenants.sql

package queries

import (
	"context"
	"encoding/json"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTenant = `-- name: CreateTenant :one

INSERT INTO tenants (
    name, slug, business_type, country_code, base_currency, timezone
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, name, slug, business_type, country_code, base_currency, timezone, metadata, created_at, updated_at
`

type CreateTenantParams struct {
	Name         string      `db:"name" json:"name"`
	Slug         string      `db:"slug" json:"slug"`
	BusinessType pgtype.Text `db:"business_type" json:"business_type"`
	CountryCode  pgtype.Text `db:"country_code" json:"country_code"`
	BaseCurrency pgtype.Text `db:"base_currency" json:"base_currency"`
	Timezone     pgtype.Text `db:"timezone" json:"timezone"`
}

// sql/queries/tenants.sql
func (q *Queries) CreateTenant(ctx context.Context, arg CreateTenantParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, createTenant,
		arg.Name,
		arg.Slug,
		arg.BusinessType,
		arg.CountryCode,
		arg.BaseCurrency,
		arg.Timezone,
	)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.BusinessType,
		&i.CountryCode,
		&i.BaseCurrency,
		&i.Timezone,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantByID = `-- name: GetTenantByID :one
SELECT id, name, slug, business_type, country_code, base_currency, timezone, metadata, created_at, updated_at FROM tenants 
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetTenantByID(ctx context.Context, id uuid.UUID) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantByID, id)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.BusinessType,
		&i.CountryCode,
		&i.BaseCurrency,
		&i.Timezone,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTenantBySlug = `-- name: GetTenantBySlug :one
SELECT id, name, slug, business_type, country_code, base_currency, timezone, metadata, created_at, updated_at FROM tenants 
WHERE slug = $1 LIMIT 1
`

func (q *Queries) GetTenantBySlug(ctx context.Context, slug string) (Tenant, error) {
	row := q.db.QueryRow(ctx, getTenantBySlug, slug)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.BusinessType,
		&i.CountryCode,
		&i.BaseCurrency,
		&i.Timezone,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTenantsByUser = `-- name: ListTenantsByUser :many
SELECT t.id, t.name, t.slug, t.business_type, t.country_code, t.base_currency, t.timezone, t.metadata, t.created_at, t.updated_at FROM tenants t
JOIN tenant_users tu ON t.id = tu.tenant_id
WHERE tu.user_id = $1
ORDER BY t.created_at DESC
`

func (q *Queries) ListTenantsByUser(ctx context.Context, userID uuid.UUID) ([]Tenant, error) {
	rows, err := q.db.Query(ctx, listTenantsByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Tenant{}
	for rows.Next() {
		var i Tenant
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Slug,
			&i.BusinessType,
			&i.CountryCode,
			&i.BaseCurrency,
			&i.Timezone,
			&i.Metadata,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTenantMetadata = `-- name: UpdateTenantMetadata :one
UPDATE tenants 
SET metadata = $2, updated_at = NOW()
WHERE id = $1
RETURNING id, name, slug, business_type, country_code, base_currency, timezone, metadata, created_at, updated_at
`

type UpdateTenantMetadataParams struct {
	ID       uuid.UUID       `db:"id" json:"id"`
	Metadata json.RawMessage `db:"metadata" json:"metadata"`
}

func (q *Queries) UpdateTenantMetadata(ctx context.Context, arg UpdateTenantMetadataParams) (Tenant, error) {
	row := q.db.QueryRow(ctx, updateTenantMetadata, arg.ID, arg.Metadata)
	var i Tenant
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Slug,
		&i.BusinessType,
		&i.CountryCode,
		&i.BaseCurrency,
		&i.Timezone,
		&i.Metadata,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
